# Generated by Django 4.2.1 on 2023-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cadeira', models.CharField(max_length=100)),
                ('gitLink', models.CharField(max_length=100)),
                ('tecnologies', models.CharField(max_length=100)),
                ('utubeLink', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('programmers', models.ManyToManyField(related_name='projects', to='portfolio.programmer')),
            ],
        ),
    ]
