# Generated by Django 4.2.1 on 2023-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='programmers',
            field=models.ManyToManyField(to='portfolio.programmer'),
        ),
    ]
