# Generated by Django 4.2.1 on 2023-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_lab_news_tecnologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=10)),
                ('birth', models.DateTimeField()),
                ('creator', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='portfolio/')),
                ('site', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Tecnologies',
        ),
    ]
