# Generated by Django 4.2.1 on 2023-06-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_technologies_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
