# Generated by Django 4.2.1 on 2023-06-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_technologies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
