# Generated by Django 4.2.1 on 2023-06-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_technologies_usedinweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
