# Generated by Django 4.2.1 on 2023-06-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_author_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.AddField(
            model_name='programmer',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programmer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
